name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install g++ make cmake libmosquitto-dev
      - name: Build & install
        run: |
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build
